### ISSUE TITLE
Unable to start SFTP Pod on kubernetes

### ISSUE THREAD

**Issue by Shivanshu-Mishra** [emberstack/docker-sftp#4]
Hi ,

After installing `emberstack/sftp` helm chart , Pod is crashing with below error. Can you please helm me understand what is missing.

019-12-17 14:55:27.094 [INF] (ES.SFTP.Host.Program) Starting host
2019-12-17 14:55:27.398 [INF] (Microsoft.Hosting.Lifetime) Now listening on: http://[::]:80
2019-12-17 14:55:27.401 [DBG] (ES.SFTP.Host.HostedService) Starting
2019-12-17 14:55:27.402 [DBG] (ES.SFTP.Host.Orchestrator) Starting
2019-12-17 14:55:27.428 [FTL] (ES.SFTP.Host.Program) Host terminated unexpectedly
System.IO.FileNotFoundException: Could not find file '/app/config/sssd.conf'.
File name: '/app/config/sssd.conf'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at ES.SFTP.Host.Orchestrator.ConfigureAuthentication() in /src/ES.SFTP.Host/Orchestrator.cs:line 92
   at ES.SFTP.Host.Orchestrator.Start() in /src/ES.SFTP.Host/Orchestrator.cs:line 62
   at ES.SFTP.Host.HostedService.StartAsync(CancellationToken cancellationToken) in /src/ES.SFTP.Host/HostedService.cs:line 25
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at ES.SFTP.Host.Program.Main(String[] args) in /src/ES.SFTP.Host/Program.cs:line 33

Thanks & Regards

**Comment by winromulus** [comment]
@Shivanshu-Mishra can you provide the installation values (change any credentials used).
It looks like something is removing the sssd.conf file (used for LDAP/AD authentication).

**Comment by Shivanshu-Mishra** [comment]
Hi @winromulus  ,

I tried with default value to see how things come up.
I followed this user guide https://hub.helm.sh/charts/emberstack/sftp.

Thanks & Regards

**Comment by winromulus** [comment]
@Shivanshu-Mishra Give me until the end of day today and I'll look into this.
I introduced a new feature to support LDAP and Active Directory and it might have an issue with the default values.

**Comment by Shivanshu-Mishra** [comment]
Thanks for consideration @winromulus

**Comment by winromulus** [comment]
@Shivanshu-Mishra give version 2.0.1 a spin. It should fix your issue.
